name: run evry 5 minutes
on:
  schedule:
    - cron: '0 5 * * *'
jobs:
  demo-job:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: executr bash code
        run: |
          echo "hellow World"



# on:
#   push:
#     branches_ignore:
#       - main